//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOORUL.Model.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        private static DataBaseEntities context;
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static DataBaseEntities GetContext()
        {
            if(context == null)
                context = new DataBaseEntities();
            return context;
        }
    
        public virtual DbSet<Accaunts> Accaunts { get; set; }
        public virtual DbSet<Access> Access { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Fittings> Fittings { get; set; }
        public virtual DbSet<materials> materials { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Product_Fittings> Product_Fittings { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Products_Materials> Products_Materials { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
