//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOORUL.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_order { get; set; }
        public int id_client { get; set; }
        public int id_worker { get; set; }
        public int id_products { get; set; }
        public string description { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Products Products { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
