//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOORUL.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Fittings
    {
        public int id_Prod_Fittings { get; set; }
        public Nullable<int> id_Products { get; set; }
        public Nullable<int> id_Fittings { get; set; }
        public Nullable<int> countNeeded { get; set; }
    
        public virtual Fittings Fittings { get; set; }
        public virtual Products Products { get; set; }
    }
}
