//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOORUL.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Materials
    {
        public int id_prodMater { get; set; }
        public int id_product { get; set; }
        public int id_materials { get; set; }
        public Nullable<int> countNeeded { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
